name: Polaco
favicon: null
layout_spectrum: 0.757483390159905
typography_spectrum: 0.33809937653131783
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9528737429063767
  lightness: 0.25979005568660796
  saturation: 0.11149563454091549
  rhythmicContrast: 0.06873350706882775
purpose: []
